import {
  School,
  Student,
  Program,
  ActivityLog,
  AIWritingSubmission,
  GlobalPlatformConfig,
  Announcement,
  NotificationTemplate,
} from "../types";

export const INITIAL_PLATFORM_CONFIG: GlobalPlatformConfig = {
  superAdminWhatsapp: "https://wa.me/33612345678",
  platformName: "LinguaFlow SaaS",
  supportEmail: "support@linguaflow.io",
  primaryBrandColor: "#6D5DFC",
  aiCorrectionStrictness: "standard",
  aiCorrectionTemperature: 0.3,
  maintenanceMode: false,
};

export const INITIAL_SCHOOLS: School[] = [
  {
    id: "school-berlin",
    name: "Berlin Sprachzentrum",
    slug: "berlin-sprachzentrum",
    language: "german",
    logo: "🇩🇪",
    primaryColor: "#6366f1",
    secondaryColor: "#06b6d4",
    professionalEmail: "contact@berlin-sprachzentrum.de",
    phone: "+49 30 12345678",
    address: "Friedrichstraße 120",
    city: "Berlin",
    country: "Allemagne",
    managerName: "Klaus Weber",
    managerEmail: "klaus@berlin-sprachzentrum.de",
    managerPhone: "+49 151 23456789",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    status: "active",
    whatsappSupportUrl: "https://wa.me/491512345678",
    studentQuota: 250,
    programsCount: 2,
    createdAt: "2026-01-10",
    lastActiveDate: "2026-08-26 11:30",
  },
  {
    id: "school-milano",
    name: "Milano Lingua Studio",
    slug: "milano-lingua-studio",
    language: "italian",
    logo: "🇮🇹",
    primaryColor: "#10b981",
    secondaryColor: "#f59e0b",
    professionalEmail: "info@milanolingua.it",
    phone: "+39 02 98765432",
    address: "Via Montenapoleone 18",
    city: "Milan",
    country: "Italie",
    managerName: "Chiara Rossi",
    managerEmail: "chiara@milanolingua.it",
    managerPhone: "+39 345 1234567",
    startDate: "2026-02-01",
    endDate: "2026-11-30",
    status: "active",
    whatsappSupportUrl: "https://wa.me/393451234567",
    studentQuota: 180,
    programsCount: 2,
    createdAt: "2026-02-05",
    lastActiveDate: "2026-08-26 10:15",
  },
  {
    id: "school-europa",
    name: "Institut Européen des Langues",
    slug: "institut-europeen-langues",
    language: "both",
    logo: "🇪🇺",
    primaryColor: "#3b82f6",
    secondaryColor: "#8b5cf6",
    professionalEmail: "contact@institut-europeen-langues.com",
    phone: "+33 3 88 12 34 56",
    address: "Place de la République 14",
    city: "Strasbourg",
    country: "France",
    managerName: "Marc Dubois",
    managerEmail: "direction@institut-europeen-langues.com",
    managerPhone: "+33 6 98 76 54 32",
    startDate: "2026-01-15",
    endDate: "2026-12-31",
    status: "active",
    whatsappSupportUrl: "https://wa.me/33698765432",
    studentQuota: 300,
    programsCount: 3,
    createdAt: "2026-01-15",
    lastActiveDate: "2026-08-26 09:40",
  },
  {
    id: "school-munchen",
    name: "München Elite Kolleg",
    slug: "munchen-elite-kolleg",
    language: "german",
    logo: "🏰",
    primaryColor: "#3b82f6",
    secondaryColor: "#8b5cf6",
    professionalEmail: "kontakt@muenchen-kolleg.de",
    phone: "+49 89 55443322",
    address: "Maximilianstraße 45",
    city: "Munich",
    country: "Allemagne",
    managerName: "Stefan Gruber",
    managerEmail: "stefan@muenchen-kolleg.de",
    managerPhone: "+49 176 11223344",
    startDate: "2026-03-01",
    endDate: "2026-09-30",
    status: "active",
    whatsappSupportUrl: "https://wa.me/491761122334",
    studentQuota: 100,
    programsCount: 1,
    createdAt: "2026-03-01",
    lastActiveDate: "2026-08-25 14:10",
  },
  {
    id: "school-firenze",
    name: "Firenze Accademia Dante",
    slug: "firenze-accademia-dante",
    language: "italian",
    logo: "🏛️",
    primaryColor: "#ec4899",
    secondaryColor: "#f43f5e",
    professionalEmail: "segreteria@dante-firenze.it",
    phone: "+39 055 8765432",
    address: "Piazza del Duomo 8",
    city: "Florence",
    country: "Italie",
    managerName: "Elena Moretti",
    managerEmail: "elena@dante-firenze.it",
    managerPhone: "+39 320 9988776",
    startDate: "2026-01-15",
    endDate: "2026-10-31",
    status: "suspended",
    suspensionReason: "Audit annuel de convention linguistique en cours",
    whatsappSupportUrl: "https://wa.me/393209988776",
    studentQuota: 75,
    programsCount: 1,
    createdAt: "2026-01-15",
    lastActiveDate: "2026-08-20 16:50",
  },
];

export const INITIAL_PROGRAMS: Program[] = [
  {
    id: "prog-de-a1",
    schoolId: "school-berlin",
    schoolName: "Berlin Sprachzentrum",
    language: "german",
    title: "Allemand Débutant A1 - Fondations & Immersion",
    level: "A1",
    description: "Parcours complet de niveau A1 selon le cadre CECRL : salutations, grammaire fondamentale, verbes de base et dialogues du quotidien à Berlin.",
    thumbnail: "https://images.unsplash.com/photo-1528728329032-2972f65dfb3f?auto=format&fit=crop&w=800&q=80",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    isPublished: true,
    status: "published",
    enrolledStudentsCount: 28,
    totalVideosCount: 6,
    totalResourcesCount: 4,
    modules: [
      {
        id: "mod-de-1",
        programId: "prog-de-a1",
        title: "Module 1 : Saluer, se présenter et briser la glace",
        order: 1,
        description: "Maîtriser les formules de politesse, l'alphabet et la présentation personnelle en allemand.",
        lessons: [
          {
            id: "les-de-1",
            moduleId: "mod-de-1",
            title: "Leçon 1 : Saluer et prendre congé (Begrüßung & Abschied)",
            order: 1,
            durationMinutes: 18,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            summary: "Découvrez les salutations formelles et informelles en Allemagne, en Autriche et en Suisse alémanique.",
            theoryContent: "### Salutations courantes\n- **Hallo / Guten Tag** : Bonjour\n- **Guten Morgen** : Bonjour (le matin)\n- **Guten Abend** : Bonsoir\n- **Auf Wiedersehen / Tschüss** : Au revoir / Salut\n\n### Règle grammaticale\nEn allemand, la politesse formelle s'exprime avec le pronom **Sie** (avec majuscule) suivi du verbe conjugué au pluriel.",
            vocabulary: [
              { id: "v1", term: "Guten Tag", translation: "Bonjour", exampleSentence: "Guten Tag, Herr Müller!", exampleTranslation: "Bonjour, Monsieur Müller !" },
              { id: "v2", term: "Wie geht es Ihnen?", translation: "Comment allez-vous ?", exampleSentence: "Wie geht es Ihnen heute?", exampleTranslation: "Comment allez-vous aujourd'hui ?" },
              { id: "v3", term: "Auf Wiedersehen", translation: "Au revoir", exampleSentence: "Auf Wiedersehen und bis morgen!", exampleTranslation: "Au revoir et à demain !" },
            ],
            quiz: [
              {
                id: "q-de-1",
                question: "Quelle salutation est la plus formelle le matin ?",
                options: ["Tschüss", "Guten Morgen", "Servus", "Bis bald"],
                correctIndex: 1,
                explanation: "'Guten Morgen' est la formule formelle utilisée le matin jusqu'à environ 11h.",
              },
              {
                id: "q-de-2",
                question: "Que signifie 'Wie geht es dir ?' ?",
                options: ["D'où viens-tu ?", "Quel âge as-tu ?", "Comment vas-tu ?", "Où habites-tu ?"],
                correctIndex: 2,
                explanation: "'Wie geht es dir ?' est la formulation informelle pour demander des nouvelles.",
              },
            ],
            resources: [
              { id: "r1", title: "Fiche récapitulative Salutations A1 (PDF)", type: "pdf", url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf", sizeMb: 1.2 },
            ],
            isUnlocked: true,
            isMandatory: true,
          },
          {
            id: "les-de-2",
            moduleId: "mod-de-1",
            title: "Leçon 2 : Se présenter et épeler son nom",
            order: 2,
            durationMinutes: 22,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            summary: "Apprenez à dire d'où vous venez, votre profession et à épeler votre nom avec l'alphabet allemand.",
            theoryContent: "### Verbes essentiels\n- **heißen** : s'appeler (Ich heiße...)\n- **sein** : être (Ich bin...)\n- **kommen aus** : venir de (Ich komme aus Frankreich...)\n- **wohnen in** : habiter à (Ich wohne in Berlin...)",
            vocabulary: [
              { id: "v4", term: "Ich heiße", translation: "Je m'appelle", exampleSentence: "Ich heiße Romaric.", exampleTranslation: "Je m'appelle Romaric." },
              { id: "v5", term: "Ich komme aus", translation: "Je viens de", exampleSentence: "Ich komme aus Frankreich.", exampleTranslation: "Je viens de France." },
            ],
            quiz: [
              {
                id: "q-de-3",
                question: "Complétez : 'Ich _____ aus Paris.'",
                options: ["wohne", "heiße", "komme", "bin"],
                correctIndex: 2,
                explanation: "On utilise 'kommen aus' pour exprimer l'origine géographique.",
              },
            ],
            isUnlocked: true,
            isMandatory: true,
          },
          {
            id: "les-de-3",
            moduleId: "mod-de-1",
            title: "Leçon 3 : Les chiffres et demander l'heure",
            order: 3,
            durationMinutes: 20,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
            summary: "Les nombres de 0 à 100 et la structure des horaires formels et informels.",
            isUnlocked: true,
            isMandatory: true,
          },
        ],
      },
    ],
  },
  {
    id: "prog-de-a2",
    schoolId: "school-berlin",
    schoolName: "Berlin Sprachzentrum",
    language: "german",
    title: "Allemand Intermédiaire A2 - Communication & Travail",
    level: "A2",
    description: "Approfondissement linguistique pour le travail, les déplacements et la vie courante en Allemagne.",
    thumbnail: "https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=800&q=80",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    isPublished: true,
    status: "published",
    enrolledStudentsCount: 19,
    totalVideosCount: 4,
    totalResourcesCount: 3,
    modules: [
      {
        id: "mod-de-a2-1",
        programId: "prog-de-a2",
        title: "Module 1 : Le monde professionnel et les réunions",
        order: 1,
        description: "Organiser un rendez-vous, échanger par e-mail et exprimer son accord ou désaccord.",
        lessons: [
          {
            id: "les-de-4",
            moduleId: "mod-de-a2-1",
            title: "Leçon 1 : Rédiger un e-mail professionnel",
            order: 1,
            durationMinutes: 25,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
            summary: "Formules d'ouverture, corps de message et formules de politesse en contexte d'entreprise.",
            isUnlocked: true,
            isMandatory: true,
          },
          {
            id: "les-de-5",
            moduleId: "mod-de-a2-1",
            title: "Leçon 2 : Exprimer son opinion et justifier",
            order: 2,
            durationMinutes: 30,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
            summary: "L'utilisation de 'weil' (parce que) et la place du verbe conjugué en fin de proposition subordonnée.",
            isUnlocked: false,
            isMandatory: true,
          },
        ],
      },
    ],
  },
  {
    id: "prog-it-a1",
    schoolId: "school-milano",
    schoolName: "Milano Lingua Studio",
    language: "italian",
    title: "Italien Débutant A1 - Dialogues & Pratique Quotidienne",
    level: "A1",
    description: "Apprentissage interactif de l'italien : conversation, vie quotidienne, café, restaurant et expressions idiomatiques.",
    thumbnail: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80",
    startDate: "2026-02-01",
    endDate: "2026-11-30",
    isPublished: true,
    status: "published",
    enrolledStudentsCount: 32,
    totalVideosCount: 5,
    totalResourcesCount: 4,
    modules: [
      {
        id: "mod-it-1",
        programId: "prog-it-a1",
        title: "Modulo 1 : Primi passi e saluti in Italia",
        order: 1,
        description: "Saluer, commander au bar et faire connaissance en italien.",
        lessons: [
          {
            id: "les-it-1",
            moduleId: "mod-it-1",
            title: "Lezione 1 : Ciao e Buongiorno ! I saluti essenziali",
            order: 1,
            durationMinutes: 16,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
            summary: "Distinction entre tutoiement et vouvoiement ('dare del Tu' vs 'dare del Lei').",
            theoryContent: "### Saluti in italiano\n- **Ciao** : Salut / Bonjour (informel)\n- **Buongiorno** : Bonjour (formel, le matin et la journée)\n- **Buonasera** : Bonsoir\n- **Arrivederci** : Au revoir\n\n### Dare del Lei (Politesse)\nPour vouvoyer quelqu'un, on utilise le pronom **Lei** avec le verbe à la 3ème personne du singulier.",
            vocabulary: [
              { id: "vi1", term: "Buongiorno", translation: "Bonjour", exampleSentence: "Buongiorno signora Rossi!", exampleTranslation: "Bonjour madame Rossi !" },
              { id: "vi2", term: "Piacere di conoscerti", translation: "Enchanté(e) de faire votre connaissance", exampleSentence: "Molto piacere di conoscerti.", exampleTranslation: "Très enchanté de te rencontrer." },
              { id: "vi3", term: "Come stai?", translation: "Comment vas-tu ?", exampleSentence: "Ciao Marco, come stai?", exampleTranslation: "Salut Marco, comment vas-tu ?" },
            ],
            quiz: [
              {
                id: "q-it-1",
                question: "Quelle salutation est utilisée le matin et l'après-midi de manière formelle ?",
                options: ["Buonanotte", "Buongiorno", "Ciao", "A presto"],
                correctIndex: 1,
                explanation: "'Buongiorno' s'emploie pour saluer poliment durant la journée.",
              },
            ],
            isUnlocked: true,
            isMandatory: true,
          },
          {
            id: "les-it-2",
            moduleId: "mod-it-1",
            title: "Lezione 2 : Al bar italiano - Ordinare un caffè e un cornetto",
            order: 2,
            durationMinutes: 20,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
            summary: "Commandes de boissons, formules de politesse 'Per favore' et 'Vorrei...'.",
            isUnlocked: true,
            isMandatory: true,
          },
          {
            id: "les-it-3",
            moduleId: "mod-it-1",
            title: "Lezione 3 : I numeri e chiedere il conto",
            order: 3,
            durationMinutes: 22,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4",
            summary: "Les prix, le paiement et les expressions courantes au restaurant.",
            isUnlocked: true,
            isMandatory: true,
          },
        ],
      },
    ],
  },
  {
    id: "prog-it-a2",
    schoolId: "school-milano",
    schoolName: "Milano Lingua Studio",
    language: "italian",
    title: "Italien Intermédiaire A2 - Expression & Culture",
    level: "A2",
    description: "Perfectionnement des temps du passé (Passato Prossimo vs Imperfetto) et récits de voyages.",
    thumbnail: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80",
    startDate: "2026-02-01",
    endDate: "2026-11-30",
    isPublished: true,
    status: "published",
    enrolledStudentsCount: 14,
    totalVideosCount: 4,
    totalResourcesCount: 2,
    modules: [
      {
        id: "mod-it-a2-1",
        programId: "prog-it-a2",
        title: "Modulo 1 : Raccontare un viaggio in Italia",
        order: 1,
        description: "Raconter des souvenirs et décrire des événements passés.",
        lessons: [
          {
            id: "les-it-4",
            moduleId: "mod-it-a2-1",
            title: "Lezione 1 : Il Passato Prossimo con Avere ed Essere",
            order: 1,
            durationMinutes: 28,
            videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
            summary: "Choisir le bon auxiliaire et accorder le participe passé.",
            isUnlocked: true,
            isMandatory: true,
          },
        ],
      },
    ],
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: "stu-romaric",
    schoolId: "school-berlin",
    schoolName: "Berlin Sprachzentrum",
    name: "Romaric Hirsein",
    email: "romarichirsein@gmail.com",
    phone: "+33 6 12 34 56 78",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
    enrolledProgramId: "prog-de-a1",
    level: "A1",
    startDate: "2026-06-01",
    endDate: "2026-11-30",
    status: "active",
    progressPercent: 67,
    lastActiveLessonId: "les-de-3",
    completedLessons: ["les-de-1", "les-de-2"],
    lastLoginDate: "2026-08-26 11:15",
    createdAt: "2026-06-01",
    createdBy: "klaus@berlin-sprachzentrum.de",
  },
  {
    id: "stu-sophie",
    schoolId: "school-berlin",
    schoolName: "Berlin Sprachzentrum",
    name: "Sophie Wagner",
    email: "sophie.wagner@berlin-eleve.de",
    phone: "+49 170 9876543",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80",
    enrolledProgramId: "prog-de-a2",
    level: "A2",
    startDate: "2026-04-01",
    endDate: "2026-10-31",
    status: "active",
    progressPercent: 50,
    lastActiveLessonId: "les-de-4",
    completedLessons: ["les-de-4"],
    lastLoginDate: "2026-08-25 18:20",
    createdAt: "2026-04-01",
    createdBy: "klaus@berlin-sprachzentrum.de",
  },
  {
    id: "stu-matteo",
    schoolId: "school-milano",
    schoolName: "Milano Lingua Studio",
    name: "Matteo Conti",
    email: "matteo.conti@milanolingua.it",
    phone: "+39 340 1122334",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    enrolledProgramId: "prog-it-a1",
    level: "A1",
    startDate: "2026-05-01",
    endDate: "2026-12-15",
    status: "active",
    progressPercent: 100,
    lastActiveLessonId: "les-it-3",
    completedLessons: ["les-it-1", "les-it-2", "les-it-3"],
    lastLoginDate: "2026-08-26 09:10",
    createdAt: "2026-05-01",
    createdBy: "chiara@milanolingua.it",
  },
  {
    id: "stu-giulia",
    schoolId: "school-milano",
    schoolName: "Milano Lingua Studio",
    name: "Giulia Bianchi",
    email: "giulia.bianchi@milanolingua.it",
    phone: "+39 347 5566778",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80",
    enrolledProgramId: "prog-it-a2",
    level: "A2",
    startDate: "2026-03-01",
    endDate: "2026-09-30",
    status: "active",
    progressPercent: 100,
    lastActiveLessonId: "les-it-4",
    completedLessons: ["les-it-4"],
    lastLoginDate: "2026-08-24 16:40",
    createdAt: "2026-03-01",
    createdBy: "chiara@milanolingua.it",
  },
  {
    id: "stu-alex",
    schoolId: "school-europa",
    schoolName: "Institut Européen des Langues",
    name: "Alexandre Morel",
    email: "alexandre.morel@europa-languages.eu",
    phone: "+33 6 45 67 89 01",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    enrolledProgramId: "prog-de-a1",
    level: "A1",
    startDate: "2026-06-15",
    endDate: "2026-12-31",
    status: "active",
    progressPercent: 33,
    lastActiveLessonId: "les-de-1",
    completedLessons: ["les-de-1"],
    lastLoginDate: "2026-08-26 08:30",
    createdAt: "2026-06-15",
    createdBy: "direction@institut-europeen-langues.com",
  },
  {
    id: "stu-clara",
    schoolId: "school-firenze",
    schoolName: "Firenze Accademia Dante",
    name: "Clara Dupont",
    email: "clara.dupont@firenze-eleve.it",
    phone: "+33 6 22 33 44 55",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    enrolledProgramId: "prog-it-a1",
    level: "A1",
    startDate: "2026-01-15",
    endDate: "2026-08-20",
    status: "expired",
    progressPercent: 100,
    lastActiveLessonId: "les-it-1",
    completedLessons: ["les-it-1"],
    lastLoginDate: "2026-08-19 14:00",
    createdAt: "2026-01-15",
    createdBy: "elena@dante-firenze.it",
  },
];

export const INITIAL_AI_SUBMISSIONS: AIWritingSubmission[] = [
  {
    id: "sub-1",
    studentId: "stu-romaric",
    studentName: "Romaric Hirsein",
    schoolId: "school-berlin",
    language: "german",
    level: "A1",
    topic: "Mein erster Tag in Berlin",
    studentText: "Hallo! Ich bin Romaric. Ich bin 25 Jahre alt und ich wohnen in Berlin. Berlin ist sehr schön und gross. Ich liebe die Stadt.",
    submissionDate: "2026-08-25 14:32",
    submittedAt: "2026-08-25 14:32",
    result: {
      score: { grammar: 86, vocabulary: 88, coherence: 90 },
      overallScore: 88,
      cefrEstimatedLevel: "A1",
      summary: "Très bonne production pour un niveau A1 ! Le texte est clair et agréable à lire. Attention à la conjugaison de 'wohnen' avec la 1ère personne du singulier.",
      correctedVersion: "Hallo! Ich heiße Romaric. Ich bin 25 Jahre alt und ich wohne in Berlin. Berlin ist sehr schön und groß. Ich liebe diese Stadt.",
      errors: [
        {
          category: "Grammaire",
          type: "Conjugaison",
          original: "ich wohnen",
          correction: "ich wohne",
          explanation: "Avec le pronom 'ich', la terminaison du verbe régulier est '-e' (ich wohne).",
          severity: "medium",
        },
        {
          category: "Orthographe",
          type: "Caractère spécial",
          original: "gross",
          correction: "groß",
          explanation: "En allemand standard, après une voyelle longue, on emploie le 'Eszett' (ß).",
          severity: "low",
        },
      ],
      strengths: ["Vocabulaire de base bien employé", "Structure de phrases simple et efficace", "Communication claire"],
      improvements: ["Veiller aux accords sujet-verbe", "Enrichir les adjectifs qualificatifs"],
    },
  },
  {
    id: "sub-2",
    studentId: "stu-matteo",
    studentName: "Matteo Conti",
    schoolId: "school-milano",
    language: "italian",
    level: "A1",
    topic: "Una giornata a Milano",
    studentText: "Oggi io va al bar con i miei amici. Mangiamo un cornetto e beviamo un espresso buono. Mi piace molto Milano.",
    submissionDate: "2026-08-24 16:10",
    submittedAt: "2026-08-24 16:10",
    result: {
      score: { grammar: 84, vocabulary: 90, coherence: 92 },
      overallScore: 88,
      cefrEstimatedLevel: "A1",
      summary: "Ottimo lavoro! Le texte est très bien structuré pour décrire une sortie quotidienne.",
      correctedVersion: "Oggi vado al bar con i miei amici. Mangiamo un cornetto e beviamo un ottimo espresso. Mi piace molto Milano.",
      errors: [
        {
          category: "Grammaire",
          type: "Conjugaison irrégulière",
          original: "io va",
          correction: "io vado (ou simplement 'vado')",
          explanation: "Le verbe 'andare' est irrégulier au présent : io vado, tu vai, lui/lei va.",
          severity: "medium",
        },
      ],
      strengths: ["Très bon lexique de la vie quotidienne", "Fluidité du récit"],
      improvements: ["Réviser le présent des verbes irréguliers (andare, fare, venire)"],
    },
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: "log-1",
    action: "Création d'établissement",
    details: "Super Admin a validé l'ouverture de l'espace 'Berlin Sprachzentrum' (250 élèves max).",
    actorRole: "super_admin",
    actorName: "Super Admin",
    schoolName: "Berlin Sprachzentrum",
    schoolId: "school-berlin",
    entityType: "school",
    entityId: "school-berlin",
    timestamp: "2026-08-26 09:00:00",
    status: "success",
  },
  {
    id: "log-2",
    action: "Attribution de programme",
    details: "Berlin Sprachzentrum a inscrit Romaric Hirsein au programme Allemand Débutant A1.",
    actorRole: "school_admin",
    actorName: "Klaus Weber",
    schoolName: "Berlin Sprachzentrum",
    schoolId: "school-berlin",
    entityType: "student",
    entityId: "stu-romaric",
    timestamp: "2026-08-26 09:30:00",
    status: "success",
  },
  {
    id: "log-3",
    action: "Complétion de leçon",
    details: "Romaric Hirsein a validé la Leçon 2 : 'Se présenter et épeler son nom' (Quiz réussi à 100%).",
    actorRole: "student",
    actorName: "Romaric Hirsein",
    schoolName: "Berlin Sprachzentrum",
    schoolId: "school-berlin",
    entityType: "program",
    entityId: "les-de-2",
    timestamp: "2026-08-26 11:15:00",
    status: "success",
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-1",
    title: "Bienvenue sur LinguaFlow v2.5",
    titleFr: "Bienvenue sur LinguaFlow v2.5",
    titleEn: "Welcome to LinguaFlow v2.5",
    content: "La plateforme intègre désormais les filigranes vidéo dynamiques et le moteur d'évaluation d'expression écrite CECRL pour l'Allemand et l'Italien.",
    contentFr: "La plateforme intègre désormais les filigranes vidéo dynamiques et le moteur d'évaluation d'expression écrite CECRL pour l'Allemand et l'Italien.",
    contentEn: "The platform now features dynamic video watermarking and CEFR writing evaluation engines for German & Italian.",
    target: "all",
    priority: "info",
    createdAt: "2026-08-26 08:00",
    authorName: "Direction LinguaFlow",
    isActive: true,
  },
];

export const INITIAL_TEMPLATES: NotificationTemplate[] = [
  {
    id: "tpl-1",
    trigger: "school_created",
    title: "Bienvenue sur LinguaFlow",
    messageTemplate: "Bonjour {school_name}, votre espace d'apprentissage a été créé avec succès.",
    channel: "email",
  },
  {
    id: "tpl-2",
    trigger: "access_expiring_soon",
    title: "Votre accès expire bientôt",
    messageTemplate: "Bonjour {student_name}, il vous reste {days_left} jours d'accès à votre formation.",
    channel: "in_app",
  },
];

export interface StoredPlatformData {
  schools: School[];
  students: Student[];
  programs: Program[];
  logs: ActivityLog[];
  config: GlobalPlatformConfig;
  announcements: Announcement[];
  templates: NotificationTemplate[];
  submissions: AIWritingSubmission[];
  aiSubmissions: AIWritingSubmission[];
}

const STORAGE_KEY = "linguaflow_data_v2_5";

export function getStoredData(): StoredPlatformData {
  if (typeof window === "undefined") {
    return {
      schools: INITIAL_SCHOOLS,
      students: INITIAL_STUDENTS,
      programs: INITIAL_PROGRAMS,
      logs: INITIAL_LOGS,
      config: INITIAL_PLATFORM_CONFIG,
      announcements: INITIAL_ANNOUNCEMENTS,
      templates: INITIAL_TEMPLATES,
      submissions: INITIAL_AI_SUBMISSIONS,
      aiSubmissions: INITIAL_AI_SUBMISSIONS,
    };
  }

  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      return {
        schools: parsed.schools?.length ? parsed.schools : INITIAL_SCHOOLS,
        students: parsed.students?.length ? parsed.students : INITIAL_STUDENTS,
        programs: parsed.programs?.length ? parsed.programs : INITIAL_PROGRAMS,
        logs: parsed.logs?.length ? parsed.logs : INITIAL_LOGS,
        config: parsed.config || INITIAL_PLATFORM_CONFIG,
        announcements: parsed.announcements?.length ? parsed.announcements : INITIAL_ANNOUNCEMENTS,
        templates: parsed.templates?.length ? parsed.templates : INITIAL_TEMPLATES,
        submissions: parsed.submissions?.length ? parsed.submissions : INITIAL_AI_SUBMISSIONS,
        aiSubmissions: parsed.aiSubmissions?.length ? parsed.aiSubmissions : INITIAL_AI_SUBMISSIONS,
      };
    }
  } catch (err) {
    console.warn("Storage parse error, using default initial data", err);
  }

  return {
    schools: INITIAL_SCHOOLS,
    students: INITIAL_STUDENTS,
    programs: INITIAL_PROGRAMS,
    logs: INITIAL_LOGS,
    config: INITIAL_PLATFORM_CONFIG,
    announcements: INITIAL_ANNOUNCEMENTS,
    templates: INITIAL_TEMPLATES,
    submissions: INITIAL_AI_SUBMISSIONS,
    aiSubmissions: INITIAL_AI_SUBMISSIONS,
  };
}

export function saveStoredData(data: StoredPlatformData): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch (err) {
    console.error("Storage save error", err);
  }
}
